kind: secret
name: password
data: LcQd7xY+auTT0swh4fgJCABMwutHITWvNaxoU2QFQRsaCJwj7rVehQDCdjE=

---
kind: pipeline
type: ssh
name: default

server:
  host: vps1.aydan.dev
  user: root
  password:
    from_secret: password

steps:
- name: greeting
  commands:
  - echo hello world
