kind: pipeline
type: ssh
name: SSH

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key
    
steps:
- name: build
  commands:
  - npm ci
  - npm run build
