kind: pipeline
type: docker
name: Docker

steps:
- name: Install
  image: node
  commands:
  - npm ci
- name: Build
  image: node
  enviroment:
    demo:
      from_secret: test
  commands:
  - npm run build
  - echo $demo
  when:
    branch:
    - main
