kind: pipeline
type: docker
name: Docker

steps:
- name: Install
  image: node
  commands:
  - npm ci
- name: Build
  image: node
  commands:
  - npm run build
  
  
---
kind: pipeline
name: Docker Image

- name: build  
  image: plugins/docker
  settings:
    repo: WhyAydan/CS-Auto-Thread
    auto_tag: true
    registry: ghcr.io
    auth:
      from_secret: github
    dockerfile: Dockerfile
