kind: pipeline
type: docker
name: Docker

environment:
  demo:
    from_secret: test

steps:
- name: Install
  image: node
  commands:
  - npm ci
- name: Build
  image: node
  commands:
  - npm run build
  - echo $demo
  when:
    branch:
    - main
