kind: pipeline
type: ssh
name: SSH

server:
  host:
    from_secret: host
  user:
    from_secret: username
  password:
    from_secret: password
    
steps:
- name: build
  commands:
  - npm ci
  - npm run build
