services:
  at:
    image: ghcr.io/whyaydan/cs-auto-thread:latest
    restart: unless-stopped
    environment:
      - DISCORD_API_TOKEN=
      - SLACK_WEBHOOK_URL=

    # OPTIONAL: Pass in a .env file rather than specifying it here
    # env_file:
    #   - .env

    # OPTIONAL: Use a named volume instead of an anonymous one
    # volumes:
    #   - /some/configs/directory:/configs
